--- #YAML:1.0
name:               CouchDB-Simple
version:            0.0001
abstract:           A simple interface to CouchDB
author:
    - Khaled Hussein <khaled.hussein@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:            0
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
